 mongo:  
  image: mongo:3.0.4  
  ports:  
   - "27017:27017"  
  volumes:  
   - './data:/data/db'  
 application:  
  build: .  
  command: bash -c "yarn install; nodemon src/server.js --color=always"  
  ports:  
   - "3333:3333"  
   - "5858:5858"  
  volumes:  
   - ./app:/usr/src/app  
  links:  
   - mongo